set_property PACKAGE_PIN A8 [get_ports {LEDS[0]}]
set_property PACKAGE_PIN L15 [get_ports {LEDS[1]}]
set_property PACKAGE_PIN R17 [get_ports {LEDS[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[2]}]
set_property PULLDOWN true [get_ports reset]
